name: luxecase_admin
description: "A Flutter application for LuceCase Admin panel."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  dio: ^5.4.0
  flutter_secure_storage: ^9.0.0
  jwt_decoder: ^2.0.1
  intl: ^0.19.0
  google_fonts: ^6.1.0
  fl_chart: ^0.66.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true